### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by cs-util** [tonithenhausen/EntityFrameworkCore.TemporalTables#1]
Hi @tonithenhausen it would be great if you could add a license file to this repo so that I can consider using it, github has templates for the common open source lincenses like MIT and Apache (see https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository )

Thanks!

**Comment by tonithenhausen** [comment]
I have added the file.
